-- 新增默认现代风格邮件模板（幂等）
INSERT INTO sys_mail_template (name, code, subject, content, is_default, enabled)
SELECT
    '现代通知模板',
    'modern_notification',
    '【{{app_name}}】{{title}}',
    '<!DOCTYPE html>\n<html lang="zh-CN">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>{{title}}</title>\n</head>\n<body style="margin:0;padding:0;background:#f3f6fb;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,PingFang SC,Microsoft YaHei,sans-serif;">\n  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="padding:24px 12px;background:#f3f6fb;">\n    <tr>\n      <td align="center">\n        <table width="640" cellpadding="0" cellspacing="0" border="0" style="max-width:640px;width:100%;background:#ffffff;border-radius:16px;overflow:hidden;">\n          <tr>\n            <td style="padding:28px 28px 22px;background:linear-gradient(135deg,#0f766e,#0ea5e9);">\n              <div style="font-size:12px;color:rgba(255,255,255,0.82);letter-spacing:.5px;">{{app_name}}</div>\n              <div style="margin-top:10px;font-size:24px;line-height:1.35;color:#ffffff;font-weight:700;">{{title}}</div>\n            </td>\n          </tr>\n          <tr>\n            <td style="padding:24px 28px 8px;color:#1f2937;font-size:15px;line-height:1.85;">\n              <p style="margin:0 0 12px 0;">{{greeting}}</p>\n              <p style="margin:0;white-space:pre-line;">{{message}}</p>\n            </td>\n          </tr>\n          <tr>\n            <td style="padding:20px 28px 6px;">\n              <table cellpadding="0" cellspacing="0" border="0">\n                <tr>\n                  <td style="border-radius:10px;background:#0f766e;">\n                    <a href="{{action_url}}" style="display:inline-block;padding:12px 20px;font-size:14px;line-height:14px;color:#ffffff;text-decoration:none;font-weight:600;">{{action_text}}</a>\n                  </td>\n                </tr>\n              </table>\n            </td>\n          </tr>\n          <tr>\n            <td style="padding:18px 28px 26px;color:#6b7280;font-size:13px;line-height:1.7;">\n              <div style="padding:14px 16px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;">{{footer_note}}</div>\n              <div style="margin-top:14px;">© {{year}} {{app_name}}. All rights reserved.</div>\n            </td>\n          </tr>\n        </table>\n      </td>\n    </tr>\n  </table>\n</body>\n</html>',
    FALSE,
    TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM sys_mail_template WHERE code = 'modern_notification'
);
